# Generated by Django 5.1.1 on 2025-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapes',
            name='unique_shape',
        ),
        migrations.AddField(
            model_name='shapes',
            name='shape_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UniqueShape',
        ),
    ]
