# Generated by Django 5.1.1 on 2025-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_shapes_unique_shape_shapes_shape_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='shape',
        ),
        migrations.AddField(
            model_name='trips',
            name='shape_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
