# Generated by Django 5.1.1 on 2025-01-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gtfsdatainfo_remove_trips_shape_trips_shape_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='trip_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
