# Generated by Django 5.1.5 on 2025-02-01 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_trips_trip_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stoptimes",
            name="unique_stop",
        ),
        migrations.AddField(
            model_name="stoptimes",
            name="stop_sequence",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stoptimes",
            name="trip",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                to="website.trips",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UniqueStop",
        ),
    ]
