# Generated by Django 5.1.5 on 2025-02-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0005_remove_stoptimes_unique_stop_stoptimes_stop_sequence_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stoptimes",
            name="arrival_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stoptimes",
            name="departure_time",
            field=models.IntegerField(),
        ),
    ]
