# Generated by Django 5.1.5 on 2025-02-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_stoptimes_arrival_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripUpdate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("start_time", models.TimeField()),
                ("start_date", models.IntegerField()),
                ("schedule_relationship", models.CharField(max_length=255)),
                ("direction_id", models.SmallIntegerField()),
                ("stop_time_updates", models.JSONField()),
                ("vehicle_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="website.routes",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="website.trips"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePosition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("start_date", models.IntegerField()),
                ("schedule_relationship", models.CharField(max_length=255)),
                ("direction_id", models.SmallIntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.TimeField()),
                ("vehicle_id", models.IntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.routes"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.trips"
                    ),
                ),
            ],
        ),
    ]
