# Generated by Django 5.1.5 on 2025-02-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_archivestopupdate_archivetripupdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivestopupdate",
            name="arrival_delay",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="archivestopupdate",
            name="arrival_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="archivestopupdate",
            name="arrival_uncertainty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stopupdate",
            name="arrival_delay",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stopupdate",
            name="arrival_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stopupdate",
            name="arrival_uncertainty",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
