# Generated by Django 5.1.5 on 2025-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_archivestopupdate_departure_delay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivetripupdate",
            name="day",
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripupdate",
            name="day",
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
