# Generated by Django 5.1.5 on 2025-03-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_remove_archivestopupdate_trip_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stopupdate",
            old_name="stop_id",
            new_name="stop",
        ),
    ]
