# Generated by Django 5.1.5 on 2025-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_rename_stop_id_stopupdate_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivestopupdate",
            name="schedule_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="archivetripupdate",
            name="schedule_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="archivevehicleposition",
            name="schedule_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stopupdate",
            name="schedule_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tripupdate",
            name="schedule_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleposition",
            name="schedule_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
