# Generated by Django 5.1.5 on 2025-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_nextdelay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextdelay",
            name="delay",
            field=models.IntegerField(),
        ),
    ]
